const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
    try {
        console.log('Testing database connection...');

        // Check users
        const userCount = await prisma.user.count();
        console.log(`Current User count: ${userCount}`);

        // Create a dummy product if none exists
        const productCount = await prisma.product.count();
        if (productCount === 0) {
            console.log('No products found. Creating a test product...');
            await prisma.product.create({
                data: {
                    name: 'Test Product',
                    description: 'This is a test product generated by the seed script.',
                    price: 99.99,
                    stock: 100,
                    imageUrl: 'https://via.placeholder.com/150'
                }
            });
            console.log('Test product created!');
        } else {
            console.log(`Product count: ${productCount}`);
        }

        // List all data
        const users = await prisma.user.findMany();
        const products = await prisma.product.findMany();

        console.log('--- Current Data ---');
        console.log('Users:', users);
        console.log('Products:', products);

    } catch (e) {
        console.error('Error connecting to database:', e);
    } finally {
        await prisma.$disconnect();
    }
}

main();
